## Pool 1
[[backend_pools]]
# this matches *.whoami.localhost and whoami.localhost
matcher = "HostRegexp('(.*\\.)?whoami\\.localhost$')"
addresses = ["127.0.0.1:8084", "127.0.0.1:8085", "127.0.0.1:8086"]
strategy = { StickyCookie = { cookie_name = "lb_cookie", http_only = false, secure = false, same_site = { Lax = {} }, inner = { RoundRobin = {} } } }
chain = [
    { Compression = {} },
]
schemes = ["HTTP"]

## Pool 2
[[backend_pools]]
matcher = "Host('httpbin.localhost')"
addresses = ["172.28.1.1:80", "172.28.1.2:80", "172.28.1.3:80"]
strategy = { Random = {} }
chain = [
    { Compression = {} },
]
schemes = ["HTTP"]

## Pool 3
[[backend_pools]]
matcher = "Host('https.localhost')"
addresses = ["172.28.1.1:80", "172.28.1.2:80", "172.28.1.3:80"]
strategy = { IPHash = {} }
chain = [
    { HttpsRedirector = {} },
    { Compression = {} }
]
schemes = ["HTTP", "HTTPS"]

## Pool 4
[[backend_pools]]
matcher = "Host('www.arlb.de')"
addresses = ["172.28.1.1:80", "172.28.1.2:80", "172.28.1.3:80"]
strategy = { Random = {} }
chain = [
    { Compression = {} }
]
schemes = ["HTTP", "HTTPS"]

[certificates]
"www.arlb.de" = { certificate_path = "x509/www.arlb.de.cer", private_key_path = "x509/www.arlb.de.key" }
"https.localhost" = { certificate_path = "x509/https.localhost.cer", private_key_path = "x509/https.localhost.key" }

