## Pool 1
[[backend_pools]]
host="whoami.localhost"
addresses=["127.0.0.1:8084", "127.0.0.1:8085", "127.0.0.1:8086"]
strategy={ StickyCookie = {cookie_name="lb_cookie", http_only=false, secure=false, same_site= { Lax = {} }, inner = { RoundRobin = {} }} }
protocol = { Http = {} }
chain = [
    { Compression = {} },
]

## Pool 2
[[backend_pools]]
host="httpbin.localhost"
addresses=["172.28.1.1:80", "172.28.1.2:80", "172.28.1.3:80"]
strategy={ Random = {} }
protocol = { Http = {} }
chain = [ { Compression = {} } ]

## Pool 3
[[backend_pools]]
host="https.localhost"
addresses=["172.28.1.1:80", "172.28.1.2:80", "172.28.1.3:80"]
strategy={ IPHash = {} }
protocol = { Https = { certificate_path="x509/https.localhost.cer", private_key_path="x509/https.localhost.key"  } }
chain = [ { Compression = {} } ]

## Pool 4
[[backend_pools]]
host="www.arlb.de"
addresses=["172.28.1.1:80", "172.28.1.2:80", "172.28.1.3:80"]
strategy={ Random = {} }
protocol = { Https = { certificate_path="x509/www.arlb.de.cer", private_key_path="x509/www.arlb.de.key"  } }
chain = [ { Compression = {} } ]
