# Pool 4
[[backend_pools]]
matcher = "Host('zyna.eu')"
addresses = ["localhost:8080"]
schemes = ["HTTPS"]
strategy = { Random = {} }
[backend_pools.middlewares]
Compression = {}
MaxBodySize = 256

[certificates]
"zyna.eu" = { ACME = { email = "zyna1+acme@protonmail.com", alt_names = [], persist_dir = "/home/zyna/IdeaProjects/another-rust-load-balancer/test_acme" } }
