name: Rust

on:
  push:
    branches: [bugfix/fix-windows-build]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            artifact-filename: another-rust-load-balancer
          - platform: windows-latest
            artifact-filename: another-rust-load-balancer.exe
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build | vcpkg - Windows
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: false
        if: matrix.platform == 'windows-latest'
      - name: Build | Debug - Windows
        run: |
          $VCPKG_ROOT\vcpkg install openssl-windows:x64-windows
          $VCPKG_ROOT\vcpkg install openssl:x64-windows-static
          $VCPKG_ROOT\vcpkg integrate install
          setx VCPKGRS_DYNAMIC=1 /M
          cargo build --verbose
        if: matrix.platform == 'windows-latest'
      - name: Build | Debug
        run: cargo build --verbose
        if: matrix.platform == 'ubuntu-latest'
      - name: Tests
        run: cargo test --verbose
#       - name: Build | Release
#         run: cargo build --release
#       - name: Deploy | Artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: ${{ matrix.artifact-filename }}
#           path: target/release/${{ matrix.artifact-filename }}
